language: node_js
node_js:
  - "0.10"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  -node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run

after_success:
  - codeclimate < ./src/app/coverage/lcov.info


addons:
      code_climate:
                repo_token:
                    secure: 37282e126efedf884a0359c5e66b5c9ee3e81e445f05e6242934ef1489246523
